//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATouchOfClassImages {
    
    
    public partial class photos_admin {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// PhotoManager2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager2;
        
        /// <summary>
        /// PhotoManager3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager3;
        
        /// <summary>
        /// PhotoManager10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager10;
        
        /// <summary>
        /// PhotoManager4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager4;
        
        /// <summary>
        /// PhotoManager11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager11;
        
        /// <summary>
        /// PhotoManager5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager5;
        
        /// <summary>
        /// PhotoManager6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager6;
        
        /// <summary>
        /// PhotoManager7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager7;
        
        /// <summary>
        /// PhotoManager8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager8;
        
        /// <summary>
        /// PhotoManager9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager9;
        
        /// <summary>
        /// PhotoManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager1;
        
        /// <summary>
        /// PhotoManager12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ATouchOfClassImages.PhotoManager PhotoManager12;
    }
}
